apiVersion: v1
kind: ConfigMap
metadata:
  name: menuguru-api-config
data:
  mysql_url: {{ .Values.mysqlUrl }}:{{ .Values.mysqlPort }}
  payment_user_id: "{{ .Values.payment_userId }}"
  payment_access_token: {{ .Values.payment_accessToken }}
  payment_host_webhook: {{ .Values.payment_hostWebhook }}