spring:
  application:
    name: menuguru
  profiles:
    default: docker
  jackson:
    deserialization:
      fail-on-unknown-properties: true     
---
spring:
  config:
    activate:
      on-profile:
      - local
      
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menuguru
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}      
  jpa:
    hibernate:      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
---
spring:
  config:
    activate:
      on-profile:
      - docker
      
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}/menuguru
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}      
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl        
---        
spring:
  config:
    activate:      on-profile:      - test
  sql:
    init:      mode: always
  datasource: 
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none      