replicaCount: 1

image:
  tag: "fase2"

service:
  type: LoadBalancer
  port: 8080
  cloud: aws

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  
mysqlUrl: menuguru.cu44urmo6uwb.us-east-1.rds.amazonaws.com
mysqlPort: 3306
mysql_user: YWRtaW4=
mysql_password: Skx5NUVZYm9id0NUdkl1WUZPY3g=
payment_userId: MTg5MTg0MDUxNg==
payment_accessToken: QmVhcmVyIEFQUF9VU1ItODE4MTAyODMzMzEwNDEzMy0wNzA3MjEtMjQxYjk2NGQ1ZmUzMTI2ZmFiZjFiZGM0NGZlYWZmZGUtMTg5MTg0MDUxNg==
payment_hostWebhook: http://a28336924a9234a0bbeb1818dfd6675f-5036755897fafc39.elb.us-east-1.amazonaws.com:8080