replicaCount: 1

image:
  tag: "fase1"

service:
  type: NodePort
  port: 8080

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  
mysqlUrl: menuguru.cu44urmo6uwb.us-east-1.rds.amazonaws.com
mysqlPort: 3306