replicaCount: 1

image:
  tag: "fase2"

service:
  type: NodePort
  port: 8080

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  
mysqlUrl: menuguru-db-svc
mysqlPort: 3306
mysql_user: cm9vdA==
mysql_password: Skx5NUVZYm9id0NUdkl1WUZPY3g=
payment_userId: !!string 1891840516
payment_accessToken: "Bearer APP_USR-8181028333104133-070721-241b964d5fe3126fabf1bdc44feaffde-1891840516"
payment_hostWebhook: https://webhook.site/dee62f36-c973-4eb3-920e-65f3d1793f36/menuguru/v1/orders/11/checkout