replicaCount: 1

image:
  tag: "fase2"

service:
  type: NodePort
  port: 8080

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  
mysqlUrl: menuguru-db-svc
mysqlPort: 3306
mysql_user: cm9vdA==
mysql_password: Skx5NUVZYm9id0NUdkl1WUZPY3g=