apiVersion: v1
kind: Service
metadata:
  name: menuguru-db-svc
spec:
  selector:
    menuguru.fiapprj.perisatto.com/name: database
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30306      