apiVersion: v1
kind: Pod
metadata:
  name: menuguru-api
  labels:
    menuguru.fiapprj.perisatto.com/name: api
spec:
  containers:
    - name: menuguru-db
      image: rperisatto/menuguru-api_service:latest
      env:
        - name: MYSQL_URL
          valueFrom:
            configMapKeyRef:
              name: menuguru-api-config
              key: mysql_url
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: menuguru-secret
              key: mysql_user      
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: menuguru-secret
              key: mysql_password
      ports:
        - containerPort: 8080