apiVersion: v1
kind: Service
metadata:
  name: menuguru-api-svc
spec:
  selector:
    menuguru.fiapprj.perisatto.com/name: api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080